name: spending_analytics
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  rxdart: ^0.22.6
  shared_preferences: ^0.5.6+1
  pinput: ^0.2.3
  sqflite: ^1.2.1
  toast: ^0.1.5
  http: ^0.12.0+4
  sprintf: ^4.0.2
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

